POSTGRES_PASSWORD : ${POSTGRES_PASSWORD_ENV:june12003}
POSTGRES_URL : jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB_ENV:recommendic}
POSTGRES_USER : ${POSTGRES_USER_ENV:divjazz}

EMAIL_HOST: ${EMAIL_HOST_ENV:smtp.gmail.com}
EMAIL_PORT: ${EMAIL_PORT_ENV:465}
EMAIL_ID: ${EMAIL_ID_ENV:divjazz9@gmail.com}
EMAIL_PASSWORD: ${EMAIL_PASSWORD_ENV:sizrfqvgqwocxwjb}
VERIFY_EMAIL_HOST: ${VERIFY_EMAIL_HOST_ENV:localhost}

JWT_SECRET: ${SECRET_ENV:${SECRET}}
JWT_EXPIRATION: 432_000_000

FILE_UPLOAD_IMPL : databaseFileUploadService

