POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
POSTGRES_URL : jdbc:postgresql://postgres:5432/${POSTGRES_DB}
POSTGRES_USER : ${POSTGRES_USER}

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: "divjazz03@gmail.com"
EMAIL_PASSWORD: "june12003"
VERIFY_EMAIL_HOST: localhost

JWT_SECRET: ${SECRET}
JWT_EXPIRATION: 432_000_000

FILE_UPLOAD_IMPL : databaseFileUploadService

