POSTGRES_PASSWORD : june12003
POSTGRES_URL : jdbc:postgresql://localhost:5432/recommendic
POSTGRES_USER : divjazz

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: "divjazz03@gmail.com"
EMAIL_PASSWORD: "june12003"
VERIFY_EMAIL_HOST: ""
#CLIENT_ID: ""

spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    username:
