POSTGRES_PASSWORD : ${POSTGRES_PASSWORD_ENV}
POSTGRES_URL : jdbc:postgresql://${POSTGRES_HOST_ENV}:${POSTGRES_PORT_ENV}/${POSTGRES_DB_ENV}
POSTGRES_USER : ${POSTGRES_USER_ENV:divjazz}

EMAIL_HOST: ${EMAIL_HOST_ENV}
EMAIL_PORT: ${EMAIL_PORT_ENV}
EMAIL_ID: ${EMAIL_ID_ENV}
EMAIL_PASSWORD: ${EMAIL_PASSWORD_ENV}
VERIFY_EMAIL_HOST: ${VERIFY_EMAIL_HOST_ENV}

JWT_SECRET: ${SECRET_ENV}
JWT_EXPIRATION: 432_000_000