server:
  error:
    include-binding-errors: never
    include-message: never
  tomcat:
    mbeanregistry:
      enabled: false
    accept-count: 500
    threads:
      max: ${TOMCAT_MAX_THREADS:200}
      min-spare: ${TOMCAT_MIN_SPARE:10}
    max-swallow-size: 50MB
  shutdown: graceful
  port: ${SERVER_PORT}

spring:
  application:
    name: Recommendic
  security:
    filter:
      dispatcher-types: request
  servlet:
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 30MB
  session:
    timeout: 30M
  data:
    redis:
      connect-timeout: 60000
      repositories:
        enabled: false
  cache:
    type: redis
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        jdbc:
          batch_size: 100
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          ssl:
            enable: true
    verify:
      host: ${VERIFY_EMAIL_HOST}
    username: ${EMAIL_ID}
  profiles:
    default: test
  main:
    banner-mode: off
    # lazy-initialization: true

  jmx:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
      access: read_only
    metrics:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "health,metrics"
cors:
  frontend:
    domain: ${FRONTEND_DOMAIN:http://localhost:5173}


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
app:
  cloudinary:
    cloudName: ${CLOUDINARY_CLOUD_NAME}
    apiKey: ${CLOUDINARY_API_KEY}
    apiSecret: ${CLOUDINARY_API_SECRET}
  auth:
    maxAttempts: 5
    rsa:
      privateKey: classpath:keys/private.pem
      publicKey: classpath:keys/public.pem


logging:
  level:
    org.flywaydb: info
    io.zonky.test: warn
    org.springframework.security: warn
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error


