POSTGRES_PASSWORD : ${POSTGRES_PASSWORD_env}
POSTGRES_URL : jdbc:postgresql://postgres:5432/${POSTGRES_DB_ENV}
POSTGRES_USER : ${POSTGRES_USER_ENV}

EMAIL_HOST: ${EMAIL_HOST_ENV}
EMAIL_PORT: ${EMAIL_PORT_ENV}
EMAIL_ID: ${EMAIL_ID_ENV}
EMAIL_PASSWORD: ${EMAIL_PASSWORD_ENV}
VERIFY_EMAIL_HOST: ${VERIFY_EMAIL_HOST_ENV}

JWT_SECRET: ${SECRET_ENV}
JWT_EXPIRATION: 432_000_000

FILE_UPLOAD_IMPL : databaseFileUploadService

