DROP TABLE IF EXISTS schedule_slot, appointment CASCADE;

CREATE TABLE schedule_slot
(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
    consultant_id BIGINT REFERENCES consultant(id) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL ,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL ,
    consultation_type_id BIGINT REFERENCES consultation_type (id),
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_rule TEXT,
    is_booked BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by CHARACTER VARYING(54),
    updated_by CHARACTER VARYING(54)
);

CREATE TABLE appointment (
    id  BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY NOT NULL ,
    consultation_id BIGINT REFERENCES consultation(id),
    note TEXT,
    status TEXT DEFAULT 'CONFIRMED',
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by CHARACTER VARYING(54),
    updated_by CHARACTER VARYING(54)
);