package com.divjazz.recommendic.appointment.event;

public enum AppointmentEventType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_RESCHEDULE_REQUESTED,
    APPOINTMENT_RESCHEDULE_ACCEPTED,
    CONSULTANT_FOLLOWUP_APPOINTMENT_REQUESTED,
    CONSULTANT_FOLLOWUP_APPOINTMENT_CONFIRMED,
}
